
export const products = [
    {
      id: '1',
      name: 'Casque sans fil Premium',
      price: 90000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'headphones music',
      stock: 24,
      category: 'Électronique',
    },
    {
      id: '2',
      name: 'Tracker d\'Activité Intelligent',
      price: 54000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'smart watch',
      stock: 50,
      category: 'Électronique',
    },
    {
      id: '3',
      name: 'Machine à Café Portable',
      price: 39000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'coffee maker',
      stock: 15,
      category: 'Maison',
    },
    {
      id: '4',
      name: 'Chaise de Bureau Ergonomique',
      price: 180000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'office chair',
      stock: 8,
      category: 'Mobilier',
    },
    {
      id: '5',
      name: 'T-shirt en Coton Bio',
      price: 15000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'tshirt clothes',
      stock: 120,
      category: 'Mode',
    },
    {
      id: '6',
      name: 'Baskets de Course',
      price: 75000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'sneakers shoes',
      stock: 45,
      category: 'Mode',
    },
    {
      id: '7',
      name: 'Service de Coaching en Nutrition',
      price: 25000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'healthy food',
      stock: 99,
      category: 'Services',
    },
    {
      id: '8',
      name: 'Panier de Fruits et Légumes Bio',
      price: 18000,
      image: 'https://placehold.co/600x400.png',
      dataAiHint: 'vegetable basket',
      stock: 30,
      category: 'Alimentaire',
    }
  ];
  
